- name: git clone https://github.com/sstephenson/rbenv.git /usr/local/rbenv
  become: yes
  git:
    repo: 'https://github.com/sstephenson/rbenv.git'
    dest: /usr/local/rbenv
  tags:
    - ruby
    - rbenv

- name: add rbenv initialization to profile
  template:
    src: etc/profile.d/rbenv.sh.j2
    dest: /etc/profile.d/rbenv.sh
    owner: root
    group: root
    mode: 0644
  become: yes
  tags:
    - ruby
    - rbenv
